version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build # Optional: Build your application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*' # Include all files in the output artifact